name: "Workflow Step Telemetry"
description: "A GitHub Action to automatically instrument workflow step execution and send traces to Honeycomb"
author: "Serkan Özal <serkan@thundra.io>"
inputs:
  github_token:
    description: "GitHub API Access Token"
    default: ${{ github.token }}
    required: false
  apikey:
    description: "Honeycomb API key - required to send traces to Honeycomb"
    required: true
  apihost:
    description: "Honeycomb API host"
    required: false
    default: "https://api.honeycomb.io"
  dataset:
    description: "The Honeycomb dataset to send traces to"
    required: true
  matrix-key:
    description: "Set this to a key unique for this matrix cell, only useful when using a build matrix"
    required: false
  otel-traceid:
    description: "If true, generate the trace ID as a 128-bit hex string compatible with OpenTelemetry by MD5 hashing the existing predictable trace ID"
    required: false
    default: "false"
  comment_on_pr:
    description: "Set to `true` to post a comment with the Honeycomb trace URL to the PR (applicable if workflow run is triggered from PR). Defaults to 'false'."
    default: "false"
    required: false
  job_summary:
    description: "Set to `true` to add the Honeycomb trace URL to the job summary page of the workflow run. Defaults to 'false'."
    default: "false"
    required: false

runs:
  using: "node20"
  main: dist/main/index.js
  post: dist/post/index.js
branding:
  icon: "activity"
  color: "yellow"
